/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_handwin_zeromq_ZeromqRequest */

#ifndef _Included_com_handwin_zeromq_ZeromqRequest
#define _Included_com_handwin_zeromq_ZeromqRequest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_handwin_zeromq_ZeromqRequest
 * Method:    native_init
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_handwin_zeromq_ZeromqRequest_native_1init
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_handwin_zeromq_ZeromqRequest
 * Method:    native_destory
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_handwin_zeromq_ZeromqRequest_native_1destory
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_handwin_zeromq_ZeromqRequest
 * Method:    native_send
 * Signature: (J[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_handwin_zeromq_ZeromqRequest_native_1send
  (JNIEnv *, jobject, jlong, jbyteArray ,  jint);

#ifdef __cplusplus
}
#endif
#endif
